# Generated by Django 5.0.7 on 2026-08-22 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('remind_at', models.DateTimeField()),
                ('repeat', models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Every day'), ('weekly', 'Every week')], default='none', max_length=10)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['remind_at'],
                'indexes': [models.Index(fields=['is_sent', 'remind_at'], name='reminders_r_is_sent_752909_idx')],
            },
        ),
    ]
