# Generated by Django 5.0.7 on 2026-08-22 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Web Series / TV Show'), ('documentary', 'Documentary'), ('anime', 'Anime')], default='movie', max_length=20)),
                ('industry', models.CharField(choices=[('bollywood', 'Bollywood (Indian Cinema)'), ('hollywood', 'Hollywood (Western / Global)'), ('regional', 'South Indian / Regional Cinema'), ('asian_korean', 'Korean / Asian / International')], default='bollywood', max_length=20)),
                ('genre', models.CharField(choices=[('rom_com', 'Rom-Com (Romantic Comedy)'), ('action', 'Action / Adventure'), ('drama', 'Drama'), ('thriller', 'Thriller / Suspense'), ('comedy', 'Comedy'), ('sci_fi', 'Sci-Fi / Fantasy'), ('crime', 'Crime / Mystery'), ('romance', 'Romance'), ('horror', 'Horror'), ('biography', 'Biography / History'), ('family', 'Family / Animation')], default='rom_com', max_length=30)),
                ('status', models.CharField(choices=[('watched', 'Watched (Watched Till Now)'), ('watching', 'Currently Watching'), ('plan_to_watch', 'Plan to Watch (Love to Watch)'), ('on_hold', 'On Hold'), ('dropped', 'Dropped')], default='watched', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('poster_url', models.URLField(blank=True, help_text='Poster image thumbnail URL', max_length=500)),
                ('backdrop_url', models.URLField(blank=True, max_length=500)),
                ('release_year', models.PositiveIntegerField(blank=True, help_text='e.g. 2023', null=True)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('cast', models.CharField(blank=True, help_text='Lead actors / cast', max_length=350)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, help_text='e.g. 8.4', max_digits=3, null=True)),
                ('my_rating', models.PositiveSmallIntegerField(blank=True, choices=[(10, '⭐ 10/10'), (9, '⭐ 9/10'), (8, '⭐ 8/10'), (7, '⭐ 7/10'), (6, '⭐ 6/10'), (5, '⭐ 5/10'), (4, '⭐ 4/10'), (3, '⭐ 3/10'), (2, '⭐ 2/10'), (1, '⭐ 1/10')], null=True)),
                ('review', models.TextField(blank=True, help_text='Your thoughts, review, or favorite scenes')),
                ('where_to_watch', models.CharField(blank=True, help_text='e.g. Netflix, Prime Video, Hotstar, Cinema', max_length=100)),
                ('watched_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='movies_movi_user_id_18d66a_idx'), models.Index(fields=['user', 'industry'], name='movies_movi_user_id_432cf3_idx'), models.Index(fields=['user', 'genre'], name='movies_movi_user_id_24b672_idx'), models.Index(fields=['user', 'is_favorite'], name='movies_movi_user_id_3cc494_idx')],
            },
        ),
    ]
