# Generated by Django 5.0.7 on 2026-08-22 12:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalahDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fajr', models.BooleanField(default=False)),
                ('dhuhr', models.BooleanField(default=False)),
                ('asr', models.BooleanField(default=False)),
                ('maghrib', models.BooleanField(default=False)),
                ('isha', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salah_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalahPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Jaunpur', max_length=100)),
                ('state', models.CharField(blank=True, default='Uttar Pradesh', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('method', models.IntegerField(choices=[(1, 'University of Islamic Sciences, Karachi'), (2, 'Islamic Society of North America (ISNA)'), (3, 'Muslim World League (MWL)'), (4, 'Umm Al-Qura University, Makkah'), (5, 'Egyptian General Authority of Survey'), (7, 'Institute of Geophysics, University of Tehran'), (12, 'Union des Organisations Islamiques de France'), (13, 'Diyanet İşleri Başkanlığı, Turkey'), (15, 'Moonsighting Committee Worldwide')], default=1)),
                ('school', models.IntegerField(choices=[(0, "Shafi'i / Maliki / Hanbali (Standard)"), (1, 'Hanafi (Later Asr)')], default=1)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salah_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='salahdailylog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_salah_log'),
        ),
    ]
