# Generated by Django 5.0.7 on 2026-08-22 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('religious', 'Religious / Islamic'), ('non_religious', 'Non-Religious / General'), ('self_help', 'Self-Help / Productivity'), ('fiction', 'Fiction / Novels'), ('history', 'History / Biography'), ('academic', 'Academic / Science / Tech')], default='non_religious', max_length=30)),
                ('status', models.CharField(choices=[('reading', 'Currently Reading'), ('completed', 'Completed (Read Till Now)'), ('want_to_read', 'Want to Read (Gonna Read)'), ('on_hold', 'On Hold')], default='want_to_read', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('pdf_url', models.URLField(blank=True, help_text='Direct link to free online PDF', max_length=500)),
                ('current_page', models.PositiveIntegerField(default=1)),
                ('total_pages', models.PositiveIntegerField(default=1)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '★☆☆☆☆ (1/5)'), (2, '★★☆☆☆ (2/5)'), (3, '★★★☆☆ (3/5)'), (4, '★★★★☆ (4/5)'), (5, '★★★★★ (5/5)')], null=True)),
                ('review', models.TextField(blank=True)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('quote_text', models.TextField(blank=True, help_text='Key quote or excerpt from the book')),
                ('note_text', models.TextField(help_text='Personal thoughts, lessons, or takeaways')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['page_number', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['user', 'status'], name='books_book_user_id_cf06b1_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['user', 'category'], name='books_book_user_id_3efcbd_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['user', 'is_favorite'], name='books_book_user_id_7c5c19_idx'),
        ),
    ]
