# Generated by Django 5.0.7 on 2026-08-22 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HadithBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=50)),
                ('collection_name', models.CharField(max_length=100)),
                ('hadith_number', models.CharField(max_length=30)),
                ('chapter_name', models.CharField(blank=True, max_length=200)),
                ('arabic_text', models.TextField(blank=True)),
                ('translation_text', models.TextField()),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadith_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HadithReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=50)),
                ('hadith_number', models.CharField(max_length=30)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadith_reading_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='hadithbookmark',
            constraint=models.UniqueConstraint(fields=('user', 'collection_id', 'hadith_number'), name='unique_user_hadith_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='hadithreadinglog',
            constraint=models.UniqueConstraint(fields=('user', 'collection_id', 'hadith_number'), name='unique_user_hadith_read'),
        ),
    ]
