# Generated by Django 5.0.7 on 2026-08-22 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField()),
                ('ayah_number', models.IntegerField()),
                ('surah_name', models.CharField(max_length=100)),
                ('arabic_text', models.TextField()),
                ('translation_text', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuranReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_surah', models.IntegerField(default=1)),
                ('last_ayah', models.IntegerField(default=1)),
                ('surah_name', models.CharField(default='Al-Faatiha', max_length=100)),
                ('total_ayahs_read', models.PositiveIntegerField(default=0)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quran_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuranSurahLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField()),
                ('surah_name', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_surah_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['surah_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='quranbookmark',
            constraint=models.UniqueConstraint(fields=('user', 'surah_number', 'ayah_number'), name='unique_user_quran_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='quransurahlog',
            constraint=models.UniqueConstraint(fields=('user', 'surah_number'), name='unique_user_surah_log'),
        ),
    ]
